-- ==========================================
-- SQL Script for TaskTracker Upgrades
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. Add 'enabled' and 'has_powers' columns to 'users' table
ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_powers BOOLEAN DEFAULT TRUE;

-- 2. Add 'enabled' column to 'priorities' table
ALTER TABLE priorities ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE;

-- 3. Add 'enabled' column to 'officers' table
ALTER TABLE officers ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE;

-- 4. Create new 'statuses' table
CREATE TABLE IF NOT EXISTS statuses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  enabled BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Insert default statuses
INSERT INTO statuses (name, enabled)
VALUES 
  ('pending', TRUE),
  ('partially_done', TRUE),
  ('fully_completed', TRUE),
  ('resolved', TRUE),
  ('closed', TRUE)
ON CONFLICT (name) DO NOTHING;
