-- ==========================================
-- SQL Script for TaskTracker Upgrades
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. Add account status toggles to 'users' table
ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE;

-- 2. Add granular supervisory powers to 'users' table
ALTER TABLE users ADD COLUMN IF NOT EXISTS power_assign_tasks BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS power_forward_tasks BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS power_manage_masters BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS power_manage_instructions BOOLEAN DEFAULT FALSE;

-- 3. Add 'enabled' and 'sort_order' columns to 'priorities' table
ALTER TABLE priorities ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE priorities ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;

-- 4. Add 'enabled' and 'sort_order' columns to 'officers' table
ALTER TABLE officers ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE officers ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;

-- 5. Create new 'statuses' table
CREATE TABLE IF NOT EXISTS statuses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  enabled BOOLEAN DEFAULT TRUE,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Insert default statuses
INSERT INTO statuses (name, enabled, sort_order)
VALUES 
  ('pending', TRUE, 1),
  ('partially_done', TRUE, 2),
  ('fully_completed', TRUE, 3),
  ('resolved', TRUE, 4),
  ('closed', TRUE, 5)
ON CONFLICT (name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

-- 7. Create Important Instructions table
CREATE TABLE IF NOT EXISTS instructions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  given_by TEXT NOT NULL,
  given_date DATE NOT NULL,
  details TEXT NOT NULL,
  seen_by JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
